name: english_learn
description: "英语词典"
publish_to: 'none'

version: 2.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: any
  provider: any
  image_picker: any
  json_annotation: any
  http: any
  just_audio: any
  shared_preferences: any
  cupertino_icons: any
  flutter_launcher_icons: any
  mockito: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/main.png

flutter_icons:
  android: true
  image_path: "assets/icon/main.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/main.png"