name: english_learn
description: "英语词典"
publish_to: 'none'

version: 2.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  http: ^1.2.2
  just_audio: ^0.9.44
  shared_preferences: ^2.3.5
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  mockito: ^5.4.5
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.2
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/main.png

flutter_icons:
  android: true
  image_path: "assets/icon/main.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/main.png"